name: Frontend CI Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
    paths:
      - 'client/**'  # Only trigger on changes inside the 'client' directory (frontend)
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch
    paths:
      - 'client/**'  # Only trigger on PRs that include changes in the 'client' directory

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Set up Node.js for the job
      with:
        node-version: '16'  # Specify the Node.js version you want to use

    - name: Install dependencies
      run: |
        cd client
        npm install  # Install frontend dependencies
      displayName: 'Install Frontend Dependencies'

    - name: Run frontend tests
      run: |
        cd client
        npm test  # Run frontend tests
      displayName: 'Run Frontend Tests'

    - name: Build frontend
      run: |
        cd client
        npm run build  # Build the frontend
      displayName: 'Build Frontend'
